### ISSUE TITLE
Queue improvements

### ISSUE THREAD

**Issue by ronuma** [Safe-Corp-Jiva/frontend#79]
- [x] Drag & drop functionality not working
- [x] Preload queues
- [x] Show loading

**Comment by ronuma** [comment]
Lambda Queues
lambda: single_routing_profile_switch
arn: arn:aws:lambda:us-east-1:767398119914:function:single_routing_profile_switch
url: https://eelvchlistncf6uejbr3orwmje0cijqe.lambda-url.us-east-1.on.aws/

**Comment by pKYZ** [comment]
Working on it

**Comment by ronuma** [comment]
All done
